-- create foo table
CREATE TABLE FLYWAY.FOO (
  ID              INTEGER IDENTITY PRIMARY KEY,
  DESCRIPTION     NVARCHAR(255) NOT NULL
);

-- insert two rows
INSERT INTO FLYWAY.FOO (DESCRIPTION) VALUES ('description 1');
INSERT INTO FLYWAY.FOO (DESCRIPTION) VALUES ('description 2');

COMMIT;